online_symbols = [
    "AAVEUSDT",
    "ADAUSDT",
    "ARBUSDT",
    "ATOMUSDT",
    "AVAXUSDT",
    "BARDUSDT",
    "BCHUSDT",
    "BNBUSDT",
    "BTCUSDT",
    "DOGEUSDT",
    "DOTUSDT",
    "ETCUSDT",
    "ETHUSDT",
    "HBARUSDT",
    "HYPEUSDT",
    "LINKUSDT",
    "LTCUSDT",
    "ONDOUSDT",
    "SOLUSDT",
    "TONUSDT",
    "TRUMPUSDT",
    "TRXUSDT",
    "XLMUSDT",
    "XRPUSDT",
    "WLDUSDT",
    "FILUSDT",
]
