[pnlu_factor_stream]
period_s = 5
rolling_window = 720
min_periods = 300
shift = 120
max_keep_periods = 360

[pnlu_factor_rolling]
symbols_config = "pnlu_factor_rolling_symbols.json"
redis_url = "redis://47.238.128.48:4190/0"
